import type { Metadata } from "next";
import "../../styles/globals.css";
import { manrope } from "@/styles/fonts";
import Providers from "@/components/ui/provider";

export const metadata: Metadata = {
  title: "Bytebank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${manrope.variable}`}>
      <head>
        <link rel="icon" href="./icon.svg" type="image/svg" />
      </head>
      <body className="antialiased">
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
