import type { Metadata } from "next";
import "../../styles/globals.css";
import { manrope } from "@/styles/fonts";
import Providers from "@/components/ui/provider";
import { SidebarProvider } from "@/context/sidebar-context";

export const metadata: Metadata = {
  title: "Bytebank",
  description: "Generated by create next app",
};

import AuthGuard from "@/components/auth/auth-guard";
import SidebarMenu from "@/components/ui/SidebarMenu/SidebarMenu";
import Topbar from "@/components/ui/Topbar/Topbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${manrope.variable}`}>
      <head>
        <link rel="icon" href="./icon.svg" type="image/svg" />
      </head>
      <body className="antialiased">
        <Providers>
          <AuthGuard>
            <SidebarProvider>
              <div className="flex">
                <SidebarMenu />
                <main className="flex flex-col px-4 md:px-10 py-4 w-full h-screen overflow-y-auto">
                  <Topbar />
                  {children}
                </main>
              </div>
            </SidebarProvider>
          </AuthGuard>
        </Providers>
      </body>
    </html>
  );
}
