import type { Metadata } from "next";
import "../../styles/globals.css";
import { manrope } from "@/styles/fonts";
import SidebarMenu from "@/components/ui/sidebar_menu";
import Topbar from "@/components/ui/topbar";
import Providers from "@/components/ui/provider";

export const metadata: Metadata = {
  title: "Bytebank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${manrope.variable}`}>
      <head>
        <link rel="icon" href="./icon.svg" type="image/svg" />
      </head>
      <body className="antialiased">
        <Providers>
          <div className="flex">
            <SidebarMenu />
            <main className="flex flex-col px-10 py-4 w-full h-screen overflow-y-auto">
              <Topbar />
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
