import type { Metadata } from "next";
import "../styles/globals.css";
import { manrope } from "@/styles/fonts";
import SidebarMenu from "@/components/sidebar_menu";
import { ConfigProvider } from "antd";
import theme from "@/styles/theme/theme";
import Topbar from "@/components/topbar";

export const metadata: Metadata = {
  title: "Bytebank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userName = "Joana da Silva Oliveira";
  return (
    <html lang="pt-br">
      <head>
        <link rel="icon" href="./icon.svg" type="image/svg" />
      </head>

      <body className={`${manrope.variable}`}>
        <ConfigProvider theme={theme}>
          <div className="flex flex-column">
            <SidebarMenu />

            <main className="flex flex-col px-10 py-4 w-full h-[100vh] overflow-y-auto">
              <Topbar />
              {children}
            </main>
          </div>
        </ConfigProvider>
      </body>
    </html>
  );
}
